/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as SynonymsRouteImport } from './routes/synonyms/route'
import { Route as ExplanationsRouteImport } from './routes/explanations/route'
import { Route as IndexImport } from './routes/index'
import { Route as SynonymsSynonymIdRouteImport } from './routes/synonyms/$synonymId/route'
import { Route as ExplanationsExplanationIdRouteImport } from './routes/explanations/$explanationId/route'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const SynonymsRouteRoute = SynonymsRouteImport.update({
  id: '/synonyms',
  path: '/synonyms',
  getParentRoute: () => rootRoute,
} as any)

const ExplanationsRouteRoute = ExplanationsRouteImport.update({
  id: '/explanations',
  path: '/explanations',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SynonymsSynonymIdRouteRoute = SynonymsSynonymIdRouteImport.update({
  id: '/$synonymId',
  path: '/$synonymId',
  getParentRoute: () => SynonymsRouteRoute,
} as any)

const ExplanationsExplanationIdRouteRoute =
  ExplanationsExplanationIdRouteImport.update({
    id: '/$explanationId',
    path: '/$explanationId',
    getParentRoute: () => ExplanationsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/explanations': {
      id: '/explanations'
      path: '/explanations'
      fullPath: '/explanations'
      preLoaderRoute: typeof ExplanationsRouteImport
      parentRoute: typeof rootRoute
    }
    '/synonyms': {
      id: '/synonyms'
      path: '/synonyms'
      fullPath: '/synonyms'
      preLoaderRoute: typeof SynonymsRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/explanations/$explanationId': {
      id: '/explanations/$explanationId'
      path: '/$explanationId'
      fullPath: '/explanations/$explanationId'
      preLoaderRoute: typeof ExplanationsExplanationIdRouteImport
      parentRoute: typeof ExplanationsRouteImport
    }
    '/synonyms/$synonymId': {
      id: '/synonyms/$synonymId'
      path: '/$synonymId'
      fullPath: '/synonyms/$synonymId'
      preLoaderRoute: typeof SynonymsSynonymIdRouteImport
      parentRoute: typeof SynonymsRouteImport
    }
  }
}

// Create and export the route tree

interface ExplanationsRouteRouteChildren {
  ExplanationsExplanationIdRouteRoute: typeof ExplanationsExplanationIdRouteRoute
}

const ExplanationsRouteRouteChildren: ExplanationsRouteRouteChildren = {
  ExplanationsExplanationIdRouteRoute: ExplanationsExplanationIdRouteRoute,
}

const ExplanationsRouteRouteWithChildren =
  ExplanationsRouteRoute._addFileChildren(ExplanationsRouteRouteChildren)

interface SynonymsRouteRouteChildren {
  SynonymsSynonymIdRouteRoute: typeof SynonymsSynonymIdRouteRoute
}

const SynonymsRouteRouteChildren: SynonymsRouteRouteChildren = {
  SynonymsSynonymIdRouteRoute: SynonymsSynonymIdRouteRoute,
}

const SynonymsRouteRouteWithChildren = SynonymsRouteRoute._addFileChildren(
  SynonymsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explanations': typeof ExplanationsRouteRouteWithChildren
  '/synonyms': typeof SynonymsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/explanations/$explanationId': typeof ExplanationsExplanationIdRouteRoute
  '/synonyms/$synonymId': typeof SynonymsSynonymIdRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explanations': typeof ExplanationsRouteRouteWithChildren
  '/synonyms': typeof SynonymsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/explanations/$explanationId': typeof ExplanationsExplanationIdRouteRoute
  '/synonyms/$synonymId': typeof SynonymsSynonymIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/explanations': typeof ExplanationsRouteRouteWithChildren
  '/synonyms': typeof SynonymsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/explanations/$explanationId': typeof ExplanationsExplanationIdRouteRoute
  '/synonyms/$synonymId': typeof SynonymsSynonymIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explanations'
    | '/synonyms'
    | '/about'
    | '/explanations/$explanationId'
    | '/synonyms/$synonymId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explanations'
    | '/synonyms'
    | '/about'
    | '/explanations/$explanationId'
    | '/synonyms/$synonymId'
  id:
    | '__root__'
    | '/'
    | '/explanations'
    | '/synonyms'
    | '/about'
    | '/explanations/$explanationId'
    | '/synonyms/$synonymId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplanationsRouteRoute: typeof ExplanationsRouteRouteWithChildren
  SynonymsRouteRoute: typeof SynonymsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplanationsRouteRoute: ExplanationsRouteRouteWithChildren,
  SynonymsRouteRoute: SynonymsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/explanations",
        "/synonyms",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/explanations": {
      "filePath": "explanations/route.tsx",
      "children": [
        "/explanations/$explanationId"
      ]
    },
    "/synonyms": {
      "filePath": "synonyms/route.tsx",
      "children": [
        "/synonyms/$synonymId"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/explanations/$explanationId": {
      "filePath": "explanations/$explanationId/route.tsx",
      "parent": "/explanations"
    },
    "/synonyms/$synonymId": {
      "filePath": "synonyms/$synonymId/route.tsx",
      "parent": "/synonyms"
    }
  }
}
ROUTE_MANIFEST_END */
